### PR TITLE
Feature/admin home

### PR DESCRIPTION
**Pull request by mb19**
No navigation yet, but I will set it up once this is merged into develop.

### CODE REVIEW

**Comment by tvand7093** [comment]
Looks like you didn't commit your `Stations` folder. Add that and the build will probably complete.

**Review by tvand7093 — CHANGES_REQUESTED** [review]
This is a move in the right direction I think. For now though, make the build complete successfully then we can discuss merging this more.

**Comment by mb19** [comment]
Stations folder added. I didn't think it would be required since my stations branch has not yet been merged into develop.

**Comment by tvand7093** [comment]
It wouldn't have mattered if you had removed it from your solution prior to pushing...

**Review by tvand7093 — APPROVED** [review]

**Pull request merged**
